window.ravaSiteData = {
  brand: {
    name: "RAVA Editions",
    email: "bonjour@rava-editions.com",
    productionLeadDays: 20,
  },
  defaults: {
    format: "vertical",
    finish: "ivoire-chaud",
    country: "BE",
  },
  nav: [
    { label: "Choisir", href: "#choisir" },
    { label: "Espaces", href: "#espaces" },
    { label: "Fabrication", href: "#fabrication" },
    { label: "Commander", href: "#commander" },
  ],
  assets: {
    heroCalm: {
      src: "./assets/photos/hero-lumiere-calme.webp",
      small: "./assets/photos/hero-lumiere-calme-768.webp",
      width: 1491,
      height: 1055,
    },
    pieceVertical: {
      src: "./assets/photos/piece-vertical.webp",
      small: "./assets/photos/piece-vertical-768.webp",
      width: 941,
      height: 1672,
    },
    formatHorizontal: {
      src: "./assets/photos/format-horizontal.webp",
      small: "./assets/photos/format-horizontal-768.webp",
      width: 1448,
      height: 1086,
    },
    finishesSamples: {
      src: "./assets/photos/finishes-samples.webp",
      small: "./assets/photos/finishes-samples-768.webp",
      width: 1448,
      height: 1086,
    },
    useArchitecture: {
      src: "./assets/photos/usage-architecture.webp",
      small: "./assets/photos/usage-architecture-768.webp",
      width: 1122,
      height: 1402,
    },
    useSeparation: {
      src: "./assets/photos/usage-separation.webp",
      small: "./assets/photos/usage-separation-768.webp",
      width: 1122,
      height: 1402,
    },
    useFamily: {
      src: "./assets/photos/usage-family.webp",
      small: "./assets/photos/usage-family-768.webp",
      width: 1122,
      height: 1402,
    },
    useWinterGarden: {
      src: "./assets/photos/usage-jardin-hiver.webp",
      small: "./assets/photos/usage-jardin-hiver-768.webp",
      width: 1086,
      height: 1448,
    },
    darkSalon: {
      src: "./assets/photos/dark-salon.webp",
      small: "./assets/photos/dark-salon-768.webp",
      width: 1122,
      height: 1402,
    },
    detailTexture: {
      src: "./assets/photos/detail-texture.webp",
      small: "./assets/photos/detail-texture-768.webp",
      width: 1122,
      height: 1402,
    },
    detailNiches: {
      src: "./assets/photos/detail-niches.webp",
      small: "./assets/photos/detail-niches-768.webp",
      width: 1122,
      height: 1402,
    },
    atelier: {
      src: "./assets/photos/atelier.webp",
      small: "./assets/photos/atelier-768.webp",
      width: 1122,
      height: 1402,
    },
    installation: {
      src: "./assets/photos/installation.webp",
      small: "./assets/photos/installation-768.webp",
      width: 1122,
      height: 1402,
    },
  },
  variants: {
    vertical: {
      slug: "vertical",
      code: "Piece 001",
      label: "Vertical",
      name: "Cabinet Mura vertical",
      dimensions: "102 x 184 x 42 cm",
      basePrice: 2000,
      silhouette: "./assets/mura-vertical.svg",
      usage: "Habite un mur, une entree ou un salon sans alourdir la piece.",
      hero: {
        asset: "heroCalm",
        ratio: "hero",
        position: "66% 50%",
        legend: "Piece 001 · format vertical",
        alt: "Cabinet Mura vertical dans un interieur calme et lumineux",
        sizes: "(max-width: 960px) 100vw, 52vw",
      },
      configure: {
        asset: "pieceVertical",
        ratio: "portrait",
        position: "51% 50%",
        legend: "Lecture frontale · format vertical",
        alt: "Cabinet Mura vertical en lecture frontale",
        sizes: "(max-width: 960px) 100vw, 52vw",
      },
      order: {
        asset: "useSeparation",
        ratio: "portrait",
        position: "50% 46%",
        legend: "Separer sans fermer",
        alt: "Cabinet Mura vertical utilise comme separation douce",
        sizes: "(max-width: 960px) 100vw, 50vw",
      },
    },
    horizontal: {
      slug: "horizontal",
      code: "Piece 002",
      label: "Horizontal",
      name: "Cabinet Mura horizontal",
      dimensions: "184 x 120 x 42 cm",
      basePrice: 2400,
      silhouette: "./assets/mura-horizontal.svg",
      usage: "Dessine une ligne basse, sous une fenetre ou face a un canape.",
      hero: {
        asset: "formatHorizontal",
        ratio: "landscape",
        position: "50% 56%",
        legend: "Piece 002 · format horizontal",
        alt: "Cabinet Mura horizontal dans un interieur lumineux",
        sizes: "(max-width: 960px) 100vw, 52vw",
      },
      configure: {
        asset: "formatHorizontal",
        ratio: "landscape",
        position: "50% 56%",
        legend: "Lecture frontale · format horizontal",
        alt: "Cabinet Mura horizontal en lecture frontale",
        sizes: "(max-width: 960px) 100vw, 52vw",
      },
      order: {
        asset: "formatHorizontal",
        ratio: "landscape",
        position: "50% 56%",
        legend: "Console sculpturale et separation basse",
        alt: "Cabinet Mura horizontal dans un espace de vie",
        sizes: "(max-width: 960px) 100vw, 50vw",
      },
    },
  },
  finishSwatches: [
    {
      slug: "ivoire-chaud",
      name: "Ivoire chaud",
      note: "Teinte fondatrice, douce et lumineuse.",
      color: "#e6d9c7",
      wash: "rgba(230, 217, 199, 0.16)",
      heroAsset: "heroCalm",
      sceneAsset: "useArchitecture",
      priceDelta: 0,
    },
    {
      slug: "craie",
      name: "Craie",
      note: "Blanc casse plus sec, lecture tres pure.",
      color: "#ece7df",
      wash: "rgba(238, 234, 226, 0.18)",
      heroAsset: "pieceVertical",
      sceneAsset: "pieceVertical",
      priceDelta: 0,
    },
    {
      slug: "sable",
      name: "Sable",
      note: "Chaleur plus solaire, ton editorial calme.",
      color: "#d7c2a4",
      wash: "rgba(215, 194, 164, 0.16)",
      heroAsset: "heroCalm",
      sceneAsset: "useArchitecture",
      priceDelta: 0,
    },
    {
      slug: "argile-claire",
      name: "Argile claire",
      note: "Beige dense et poudre, plus mat encore.",
      color: "#ccb39a",
      wash: "rgba(204, 179, 154, 0.18)",
      heroAsset: "useSeparation",
      sceneAsset: "useSeparation",
      priceDelta: 90,
    },
    {
      slug: "ocre-doux",
      name: "Ocre doux",
      note: "Accent plus editorial, chaleur plus enveloppante.",
      color: "#b78f66",
      wash: "rgba(183, 143, 102, 0.18)",
      heroAsset: "useFamily",
      sceneAsset: "detailNiches",
      priceDelta: 140,
    },
    {
      slug: "vert-gris",
      name: "Vert gris",
      note: "Variation sourde, calme, plus vegetale.",
      color: "#9aa393",
      wash: "rgba(154, 163, 147, 0.18)",
      heroAsset: "useWinterGarden",
      sceneAsset: "useWinterGarden",
      priceDelta: 140,
    },
    {
      slug: "charbon-doux",
      name: "Charbon doux",
      note: "Edition speciale, plus dense, plus dramatique.",
      color: "#4b4846",
      wash: "rgba(55, 52, 50, 0.2)",
      heroAsset: "darkSalon",
      sceneAsset: "darkSalon",
      priceDelta: 220,
      special: true,
    },
  ],
  shippingZones: {
    BE: {
      code: "BE",
      label: "Belgique",
      transit: "4 a 7 jours ouvres",
      note: "Livraison premium sur rendez-vous, verification des acces avant depart.",
      destination: ["BE"],
    },
    FR: {
      code: "FR",
      label: "France",
      transit: "7 a 12 jours ouvres",
      note: "Transport specialise France metropolitaine, validation logistique avant lancement.",
      destination: ["FR"],
    },
    EU: {
      code: "EU",
      label: "Autre pays UE",
      transit: "delai affine selon destination",
      note: "Etude logistique au cas par cas avant confirmation de commande.",
      destination: ["DE", "LU", "NL", "ES", "IT", "PT"],
    },
  },
  ctaModes: {
    order: {
      label: "Commander la piece",
      title: "Commander Cabinet Mura",
      subject: "Commande standard - Cabinet Mura",
      intro:
        "Recevez un recapitulatif clair de la piece, du delai et du transport avant validation finale.",
    },
    sheet: {
      label: "Recevoir la fiche technique",
      title: "Recevoir la fiche technique",
      subject: "Fiche technique - Cabinet Mura",
      intro:
        "Nous envoyons la fiche produit avec dimensions, finitions et prerequis logistiques.",
    },
    project: {
      label: "Parler du projet",
      title: "Parler de votre projet",
      subject: "Projet sur mesure - Cabinet Mura",
      intro:
        "Pour une integration architecturale, une finition particuliere ou une implantation specifique.",
    },
  },
  processSteps: [
    "Choisir le format.",
    "Valider la finition.",
    "Confirmer les acces et l'adresse.",
    "Recevoir le recapitulatif et l'estimation.",
    "Lancer la fabrication.",
  ],
};
